---
name: Test Workflow
on:
  - push
jobs:
  build:
    strategy:
      matrix:
        python-version:
          - 3.9
    runs-on: ubuntu-latest
    outputs:
      python-path: ${{ steps.setup_python.outputs.python-path }}
    steps:
      - name: Checkout Step
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.WF_ACCESS_TOKEN }}
      
      - name: Setup Python ${{ matrix.python-version }}
        id: setup_python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            python/requirements.txt

      - name: Cache dependencies
        id: save_cache
        uses: actions/cache/save@v3
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ hashFiles('python/requirements.txt') }}
      
      - name: Install dependencies
        run: |
          python -m pip install -r python/requirements.txt --use-deprecated=legacy-resolver

      - name: Print default branch
        run:
          echo ${{ env.pythonLocation }}

  job_2:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Step
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.WF_ACCESS_TOKEN }}

      - name: Pring other job output
        env:
          PY_PATH: ${{needs.build.outputs.python-path}}
        run: |
          echo "$PY_PATH"
