---
name: Test Workflow
on:
  - push
jobs:
  build:
    strategy:
      matrix:
        python-version:
          - 3.9
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Step
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.WF_ACCESS_TOKEN }}
          submodule: recursive
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          # cache: pip
          # cache-dependency-path: |
          #   python/requirements.txt
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ hashFiles('python/requirements.txt') }}
      - name: Install dependencies
        run: |
          python -m pip install -r python/requirements.txt --use-deprecated=legacy-resolver
